// 코인 심볼을 한국어 이름으로 변환하는 유틸리티
export const getKoreanCoinName = (symbol: string): string => {
  const coinNames: { [key: string]: string } = {
    'BTCUSDT': '비트코인',
    'ETHUSDT': '이더리움',
    'BNBUSDT': '바이낸스 코인',
    'ADAUSDT': '카르다노',
    'SOLUSDT': '솔라나',
    'DOTUSDT': '폴카닷',
    'LINKUSDT': '체인링크',
    'UNIUSDT': '유니스왑',
    'MATICUSDT': '폴리곤',
    'SHIBUSDT': '시바이누',
    'ETCUSDT': '이더리움 클래식',
    'XRPUSDT': '리플',
    'DOGEUSDT': '도지코인',
    'AVAXUSDT': '아발란체',
    'LTCUSDT': '라이트코인',
    'BCHUSDT': '비트코인 캐시',
    'ATOMUSDT': '코스모스',
    'NEARUSDT': '니어 프로토콜',
    'FTMUSDT': '팬텀',
    'ALGOUSDT': '알고랜드',
    'VETUSDT': '비체인',
    'ICPUSDT': '인터넷 컴퓨터',
    'FILUSDT': '파일코인',
    'TRXUSDT': '트론',
    'XLMUSDT': '스텔라',
    'HBARUSDT': '헤데라',
    'MANAUSDT': '디센트럴랜드',
    'SANDUSDT': '샌드박스',
    'AXSUSDT': '엑시 인피니티',
    'GALAUSDT': '갈라',
    'CHZUSDT': '칠리즈',
    'HOTUSDT': '홀로체인',
    'BATUSDT': '베이직 어텐션 토큰',
    'ZILUSDT': '질리카',
    'ENJUSDT': '엔진 코인',
    'ANKRUSDT': '앵커',
    'ONEUSDT': '하모니',
    'IOTAUSDT': '아이오타',
    'QTUMUSDT': '퀀텀',
    'NEOUSDT': '네오',
    'ONTUSDT': '온톨로지',
    'ZECUSDT': '지캐시',
    'DASHUSDT': '대시',
    'XMRUSDT': '모네로',
    'WAVESUSDT': '웨이브',
    'XTZUSDT': '테조스',
    'EOSUSDT': '이오스',
    'AAVEUSDT': '에이브',
    'COMPUSDT': '컴파운드',
    'MKRUSDT': '메이커다오',
    'SNXUSDT': '신세틱스',
    'CRVUSDT': '커브',
    'YFIUSDT': '연파이낸스',
    'SUSHIUSDT': '스시스왑',
    '1INCHUSDT': '1인치',
    'RENUSDT': '렌',
    'STORJUSDT': '스토리지',
    'OCEANUSDT': '오션 프로토콜',
    'BANDUSDT': '밴드 프로토콜',
    'ALPHAUSDT': '알파 파이낸스',
    'AUDIOUSDT': '오디우스',
    'RLCUSDT': '아이젝',
    'RSRUSDT': '리저브라이트',
    'OGNUSDT': '오리진 프로토콜',
    'NMRUSDT': '뉴메레어',
    'MLNUSDT': '멜론',
    'KNCUSDT': '카이버 네트워크',
    'ZRXUSDT': '0x',
    'REPUSDT': '어거',
    'LRCUSDT': '루프링',
    'OMGUSDT': '오미세고',
    'BALUSDT': '밸런서',
    'UMAUSDT': '우마',
    'PERPUSDT': '퍼페추얼 프로토콜',
    'RARIUSDT': '라리블',
    'SUPERUSDT': '슈퍼팜',
    'ALICEUSDT': '마이 네이버 앨리스',
    'FORTHUSDT': '어메스 포스',
    'PONDUSDT': '마린',
    'DYDXUSDT': 'dYdX',
    'ENSUSDT': '이더리움 네임 서비스',
    'IMXUSDT': '이뮤터블',
    'GMTUSDT': '스테픈',
    'APEUSDT': '에이프코인',
    'OPUSDT': '옵티미즘',
    'ARBUSDT': '아르비트럼',
    'INJUSDT': '인젝티브',
    'TIAUSDT': '셀레스티아',
    'JUPUSDT': '주피터',
    'PYTHUSDT': '피톤',
    'BONKUSDT': '봉크',
    'WIFUSDT': '도그위프',
    'PEPEUSDT': '페페',
    'FLOKIUSDT': '플로키',
    'BOMEUSDT': '북 오브 메메',
    'MYROUSDT': '마이로',
    'POPCATUSDT': '팝캣',
    'WENUSDT': '웬',
    'BOOKUSDT': '북',
    'TURBOUSDT': '터보',
    'SMOGUSDT': '스모그',
    'SLERFUSDT': '슬러프',
    'MEWUSDT': '캣 인 더 샷'
  };

  return coinNames[symbol] || symbol;
};
